Change outcome of CannotDecide operations
psss/fmf pull request #128
Opened 2021-04-08 15:46 UTC by lukaszachy

Implements Alex's proposal.

2021-04-08 15:48 UTC, lukaszachy commented
@t184256 Could you review please as well?

2021-04-08 16:24 UTC, t184256 reviewed
Minor formatting nitpicks inline. Logic looks OK.

I'd also like to see a testcase OR'ing on a same axis with one or both values being CannotDecide, smth like `distro < fedora-33 or distro < centos-6.9` for `fedora-33`, `fedora-34`, `centos-6.5` and `centos-7.7`. This is going to be common and I'd like to have it explicit.

2021-04-08 16:24 UTC, t184256 commented on tests/unit/test_context.py
> +            "foo=bar and distro = centos-8.2.0", # CannotDecide and True
`=` is not surrounded by whitespace, not sure if intended

2021-04-08 16:24 UTC, t184256 commented on tests/unit/test_context.py
> +        _cannot =  "baz == bar"
double space

2021-04-08 16:56 UTC, lukaszachy commented
> I'd also like to see a testcase OR'ing on a same axis with one or both values being CannotDecide, smth like `distro < fedora-33 or distro < centos-6.9` for `fedora-33`, `fedora-34`, `centos-6.5` and `centos-7.7`. This is going to be common and I'd like to have it explicit.

Extended `test_known_troublemakers` with proposed scenario.

2021-04-09 09:01 UTC, t184256 approved these changes
LGTM! I probably meant to ask for `fedora-32`, not `fedora-33`, but this should be enough as well.

2021-04-12 16:43 UTC, psss requested changes
Looks good, proposed just a couple of docs improvements.

2021-04-12 16:43 UTC, psss commented on tests/unit/test_context.py
> +        for outcome, a, op ,b in [
```suggestion
        for outcome, a, op, b in [
```

2021-04-12 16:43 UTC, psss commented on docs/context.rst
> +============  ===  ============  ============
Looking at the table I'm missing the `==` before the last column. It's a bit confusing. What about just writing theses examples as expressions?

    CannotDecide and True == CannotDecide

2021-04-12 16:43 UTC, psss commented on docs/context.rst
> +centos-8     cannot      cannot    False
```suggestion
centos-8     CannotDecide   CannotDecide   False
```

Let's use the `CannotDecide` name consistently across the whole doc.

2021-04-12 16:43 UTC, psss commented on docs/context.rst
> +compared and the expression has CannotDecide outcome::
```suggestion
compared and the expression has ``CannotDecide`` outcome::
```

2021-04-14 11:43 UTC, psss approved these changes
Looks good. Proposing to use sections to be able to link directly.

2021-04-14 11:50 UTC, lukaszachy reviewed
OK. Thanks

2021-04-14 12:40 UTC, merged